spring:
 application:
  name: stock-holding-snapshot

 data:
  mongodb:
   authentication-database: admin
   username: test
   password: test
   database: stock-trading-user
   

server:
 port: 9093

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
   defaultZone: http://localhost:9080/eureka/

instance:
 hostname: localhost


