version: '3'
services:
  axonserver:
    image: axoniq/axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:


volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind      
networks:
  default:
    name: nagp-microservice
