version: '3'
services:  
  gateway:
        build:
            context: gateway
            dockerfile: Dockerfile
        ports:
            - 9080:9080
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
                
networks: 
  default: 
      name: nagp-microservice
  