version: '3'
services:
  zookeeper:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:  
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
      - TOPICS=stock-price
  
networks: 
  default: 
    #external: 
      name: nagp-microservice  