version: '3'
services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=stock-trading-user
      - MONGO_INITDB_ROOT_ADMINUSERNAME=test
      - MONGO_INITDB_ROOT_ADMINPASSWORD=test
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    hostname: mongo-db
  
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_USERNAME=test
      - ME_CONFIG_MONGODB_PASSWORD=test
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
        - mongo-db
      
networks: 
  default: 
    #external: 
      name: nagp-microservice  