version: '3'
services:  
    auth-service:
        build:
            context: auth-service
            dockerfile: Dockerfile
        ports:
            - 9081:9081
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    
    account-balance:
        build:
            context: account-balance
            dockerfile: Dockerfile
        ports:
            - 9082:9082
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    
    bank-account-service:
        build:
            context: bank-account-service
            dockerfile: Dockerfile
        ports:
            - 9083:9083
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    
    stock-price-pull-service:
        build:
            context: stock-price-pull-service
            dockerfile: Dockerfile
        ports:
            - 9084:9084
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    
    stock-price-store-service:
        build:
            context: stock-price-store-service
            dockerfile: Dockerfile
        ports:
            - 9085:9085
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    stock-price-history:
        build:
            context: stock-price-history
            dockerfile: Dockerfile
        ports:
            - 9086:9086
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    stock-price-live:
        build:
            context: stock-price-live
            dockerfile: Dockerfile
        ports:
            - 9087:9087
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
 

    stock-price-trigger-job:
        build:
            context: stock-price-trigger-job
            dockerfile: Dockerfile
        ports:
            - 9088:9088
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    stock-price-trigger:
        build:
            context: stock-price-trigger
            dockerfile: Dockerfile
        ports:
            - 9089:9089
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    stock-trading-service:
        build:
            context: stock-trading-service
            dockerfile: Dockerfile
        ports:
            - 9090:9090
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    stock-trading-history:
        build:
            context: stock-trading-history
            dockerfile: Dockerfile
        ports:
            - 9091:9091
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    stock-holding-snapshot:
        build:
            context: stock-holding-snapshot
            dockerfile: Dockerfile
        ports:
            - 9093:9093
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"


    notification-service:
        build:
            context: notification-service
            dockerfile: Dockerfile
        ports:
            - 9094:9094
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
       
networks: 
  default: 
      name: nagp-microservice