spring:
 application:
  name: stock-price-pull-service
 kafka:
  producer:
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: com.labhi.stockprice.model.ObjectSerializer
  bootstrap-servers: localhost:9092
  template:
   defaultTopic: stock-price
 batch:
  job:
   enabled: false
  initialize-schema: always
 data:
  mongodb:
   authentication-database: admin
   username: test
   password: test
   database: stock-trading-user


job:
 execution:
  interval: 60000
  delay: 1

 
server:
 port: 9083


instance:
 hostname: localhost



