spring:
 application:
  name: stock-price-live

  

server:
 port: 9090

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
   defaultZone: http://localhost:9080/eureka/

instance:
 hostname: localhost

